#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 18 18:47:39 2022

@author: ihongseokmac2
"""

try: 
    a = int(input("Tell me one number: "))
    b = int(input("Tell me another number: "))
    print(a/b)
except:
    print("Bug in user input")
        
